name: Build & Push Docker Image (Food API)

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      # URL de BD para producción (Railway)
      DATABASE_URL: ${{ secrets.FOOD_DATABASE_URL }}
    steps:
      # 1. Chequear el código
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Preparar Node.js (para npm ci, tests o migraciones si las necesitas)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3. Crear .env para producción
      - name: Create .env file
        run: |
          echo "NODE_ENV=production"       >> .env
          echo "DATABASE_URL=${DATABASE_URL}" >> .env

      # 4. Instalar dependencias
      - name: Install dependencies
        run: npm ci

      # 5. Login a Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 6. Build y push de la imagen
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USER }}/restapi-food:${{ github.sha }}
            ${{ secrets.DOCKER_USER }}/restapi-food:latest
